config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  
  devise_for :users
  
  resources :users do
  	resources :permissions
  end
  resources :security_levels do
  	resources :pages
  	resources :permissions
  end

  resources :permissions
  resources :pages

end

app/views/pages/_form.html.erb
<%=form_for [@security_level,@page] do |form| %>

	<input id="page_controller_name" name="page[controller_name]" type="hidden">
	<input id="page_action_name" name="page[action_name]" type="hidden">
	
	<div class="form-group">
		 <select class="form-control" name="path">
            <option>Select path</option>
            <% get_routes.each do |route|%>
            	<%controller_path =route.defaults[:controller].to_s%>
	            <%if valid_route controller_path %>
	            <option> <%=controller_path+"#"+route.defaults[:action].to_s %> </option>	
	            <%end%>
            <%end%>
        </select>
    </div>

    <%= form.submit 'Add', :class => 'button right' %>
	
<%end%>

app/views/pages/_index.html.erb

<div class="container">
  <div class="row">
    <h3>Page Rights</h3>

<table class="table">
	
<%@pages.each do |page|%>
	<tr>
		<%=render page%>
	</tr>

<%end%>

</table>

<% if @security_level.level!="high" %>
	<p>
	<%=link_to "Add page accessible by this security level",new_security_level_page_path(@security_level)%>
	</p>
<%else%>
<p>This level can access all pages</p>
<%end%>
</div>
</div>

app/views/pages/_page.html.erb
<td>
  <%=page.controller_name%>#<%=page.action_name%>
</td>
<td><%=link_to "Delete Page",security_level_page_path(@security_level,page),:data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs'%></td>

app/views/pages/index.html.erb
All Pages
<%@pages.each do |page|%>
	<td>
		<%=page.controller_name%>
	</td>
	<td>
		<%=page.action_name%>
	</td>
<%end%>

app/views/pages/new.html.erb
<h2>Add Page to Security Level: <%=@security_level.level%></h2>
<%=render "form"%>