config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  
  devise_for :users
  
  resources :users do
  	resources :permissions
  end
  resources :security_levels do
  	resources :pages
  	resources :permissions
  end

  resources :permissions
  resources :pages

end

app/models/security_level.rb
class SecurityLevel < ActiveRecord::Base
	has_many :pages
	has_many :permissions	
	validates :level, uniqueness: true
end

app/controllers/security_levels_controller.rb
class SecurityLevelsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @security_level =SecurityLevel.new
    authorize SecurityLevel,"new"
  end

  def create
    authorize SecurityLevel,"create"
    @security_level = SecurityLevel.new(secure_params)
    
      if @security_level.save
        redirect_to security_levels_path, :notice => "security_levels added."
      else
        flash[:notice]="Not saved"
        redirect_to :action=>"new" 
      end 
  end

  def index
    @security_levels = SecurityLevel.all
    authorize SecurityLevel,"index"
  end
  
  def show
    @security_level = SecurityLevel.find(params[:id])
    @pages = @security_level.pages
    authorize @security_level,"show"
  end

  def update
    @security_level = SecurityLevel.find(params[:id])
    authorize @security_level,"update"
    if @security_level.update_attributes(secure_params)
      redirect_to security_levels_path, :notice => "SecurityLevel updated."
    else
      redirect_to security_levels_path, :alert => "Unable to update security_level."
    end
  end

  def destroy
    security_level = SecurityLevel.find(params[:id])
    authorize security_level,"update"
    security_level.destroy
    redirect_to security_levels_path, :notice => "Security Level deleted."
  end

  private

  def secure_params
    params.require(:security_level).permit(:level)
  end
end

app/views/security_levels/_form.html.erb
<%=form_for @security_level do |form|%>
	<div class="form-group">
      <%= form.label :level %>
      <%= form.text_field :level, :autofocus => true, class: 'form-control' %>
    </div>
    <%= form.submit 'Add', :class => 'button right' %>
<%end%>

app/views/security_levels/index.html.erb
<h2>Security Levels</h2>
	<%@security_levels.each do |security_level|%>
		<li><%=link_to security_level.level, security_level%></li>
<%end%>

<%=link_to "New Security Level",new_security_level_path%>

app/views/security_levels/new.html.erb
<h2>New Security Level</h2>
<%=render "form"%>

app/views/security_levels/show.html.erb
<h2>Security Level: <%=@security_level.level%></h2>

<%=render "pages/index"%>
