config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  
  devise_for :users
  
  resources :users do
  	resources :permissions
  end
  resources :security_levels do
  	resources :pages
  	resources :permissions
  end

  resources :permissions
  resources :pages

end

app/models/permission.rb
class Permission < ActiveRecord::Base
	belongs_to :user
	belongs_to :security_level
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
	  before_filter :authenticate_user!

	  def new
	  	@permission = Permission.new
	  	authorize Permission,"new"
	  end

	  def create 
	  	 authorize Permission,"create"
	     @permissions = Permission.new(secure_params)
	    
	     if @permission.save
	        redirect_to permissions_path, :notice => "permission added."
	     else
	        flash[:notice]="Not assigned"
	        redirect_to :action=>"new" 
	     end 
	  end 

	  def edit
	  	@permission = Permission.find(params[:id])
	  end

	  def index
	    @permissions = Permission.all
	    authorize Permission,"index"
	  end

	  def show
	    @permission = Permission.find(params[:id])
	    authorize @permission,"show"
	  end

	  def update
	    @permission = Permission.find(params[:id])
	    authorize @permission,"update"
	    if @permission.update_attributes(secure_params)
	      redirect_to permissions_path, :notice => "Permission updated."
	    else
	      redirect_to permissions_path, :alert => "Unable to update permission."
	    end
	  end

	  def destroy
	    permission = Permission.find(params[:id])
	    authorize permission,"destroy"
	    permission.destroy
	    redirect_to permissions_path, :notice => "Permission deleted."
	  end

	  private
	  	def secure_params
	  	  params.require(:permission).permit(:level_id,:user_id)
	  	end
end

app/views/permissions/_form.html.erb
<%= form_for @permission do |form| %>


    <div class="form-group">
      <%= form.label :user_id %>
       <%= select :permission, :user_id,User.all.map {|c| [c.email,c.id]},:class=>"form-control"%>
    </div>

	<div class="form-group">
      
      <%= form.label :level_id %>
      <%= select :permission, :level_id,SecurityLevel.all.map {|c| [c.level,c.id]},:class=>"form-control"%>
	    
    </div>

    <%= form.submit 'Add', :class => 'button right' %>
<% end %>

app/views/permissions/edit.html.erb
<h2>Change user Permission</h2>
<%=render "form"%>

app/views/permissions/index.html.erb
<h2>Permissions</h2>

	<%@permissions.each do |permission|%>
		<%=User.find(permission.user_id).email%> &nbsp
		<%=SecurityLevel.find(permission.level_id).level%>
		<%=link_to "Change Permission",edit_permission_path(permission)%><br>
	<%end%>

<br>

<%=link_to "New Permission",new_permission_path%>



app/views/permissions/new.html.erb
<h2>Assign user a new Permission</h2>
<%=render "form"%>